### ISSUE TITLE
download too much data outside the map canvas

### ISSUE THREAD

**Issue by stefanocudini** [lcoandrade/OSMDownloader#10]
the red rectangle is my initial canvas area... but data is also outside this area.
I think there is a bug that follows the features without ending... also outside a certain area
![downosm](https://user-images.githubusercontent.com/47107/59282268-e8b25700-8c68-11e9-9cbe-4ccca5b763f7.png)

**Comment by lcoandrade** [comment]
Hi there!
I use the overpass api to download the data. Unfortunately, the api doesn't clip the data because it would be too demanding to their servers. In the future, I'm thinking on a way to clip the data.

For now, everything that crosses the chosen rectangle is downloaded.
