### ISSUE TITLE
Does not use proxy

### ISSUE THREAD

**Issue by AnythingOverIP** [lcoandrade/OSMDownloader#11]
When Trying to download, I always get a message "Proxy set to: No proxy set."
When going to Settings / Options / Network, my proxy is well defined (i.e.: HttpProxy is configured, ans I can access OSM tiles.) If proxy is disabled, then I cannot get my tiles. 

Looks like the plugin is unable to use the proxy :|

**Comment by lcoandrade** [comment]
Bug fixed.

**Comment by patdunne** [comment]
I'm getting the same problem now. "Proxy set to: No proxy set."

**Comment by AHMEDKJALA** [comment]
even me i get same error.  firstly i uninstall plugin and reinstall its was fixed. but after two weeks same error returned and this time even reinstall not work.

**Comment by AHMEDKJALA** [comment]
i found the solution:
just try to install plugin from ZIP. and leave proxy setting un tick.
