### ISSUE TITLE
Attempts to use http proxy even when one is not set

### ISSUE THREAD

**Issue by ianturton** [lcoandrade/OSMDownloader#12]
When there is no proxy set in network settings fails to download file with error 

    Error occurred: (gaierror(-2, 'Name or service not known'),)
    Reason: [Errno -2] Name or service not known

message bar says "Proxy set to: | Port:" 

Possibly related to https://github.com/lcoandrade/OSMDownloader/issues/11

**Comment by lcoandrade** [comment]
Version 2.0.2, on QGIS 3.16 and macOS Monterey 12.2.1 didn't presented this issue. So, I'll close it. If you experience this again, let me know.
