### ISSUE TITLE
It loads the data but the symbology doesn't work in QGIS 3.12

### ISSUE THREAD

**Issue by jeabraham** [lcoandrade/OSMDownloader#14]
Downloading the data seems to work, but the rule based symbology tests for things like `"highway" is not null`.  There is no column "highway", there are just two columns, the "osm_id" and the "other_tags".  The other_tags needs to be parsed out before the symbology can be used.

**Comment by lcoandrade** [comment]
On QGIS 3.16, on my Mac OS 12.2.1 (Monterey) is working properly. If you face this again, contact me again.
