### ISSUE TITLE
Convert results to geopackage

### ISSUE THREAD

**Issue by olivierdalang** [lcoandrade/OSMDownloader#3]
Hi !

Thanks for the awesome plugin. It works really well and is extremely useful here !

On Windows/QGIS 3.3, the `.osm` file format is very slow compared to other file formats, and has other inconveniences (no row counts, etc.). From my testings, the attribute table even only displays the first 99 rows.

It would be great if the OSM downloader did the job of converting the results to a Geopackage, which also is one completely self contained file.

If you like the idea, I can probably come up with a PR for this, with a new dialog (opening up after you choose the area or through the menu, with a "don't ask again" checkbox), to choose the file format. I'd suggest making the Geopackage the default, as I think only more advanced users will prefer the .osm format.

Cheers,

Olivier

**Comment by lcoandrade** [comment]
Sorry for the late response. I like your idea. I'll wait for your PR. Thanks!
