### ISSUE TITLE
Include styles out of the box

### ISSUE THREAD

**Issue by olivierdalang** [lcoandrade/OSMDownloader#4]
Hi !

The plugin could include QGIS styles for the OSM data out of the box.

As for the other issue I just opened, if you like the idea, I could probably come up with a PR to add this, and I suggest the same ideas for the UI, e.g. a new dialog (opening up after you choose the area or through the menu, with a "don't ask again" checkbox), to choose the style.

We could start by letting choose between no style or one default style copying the standard OSM style, and maybe could over time add more possible styles (there's a few out there by several authors).

**Comment by lcoandrade** [comment]
I think we could try this!
